more cleanup

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,36 +1,66 @@
 #!/bin/sh
 
 if [ "$(uname)" = Darwin ] ; then
-    #echo "verify Xcode and git are installed"
-    [ "$(xcode-select -p)"  ] || xcode-select --install
-    [ "$(which brew)" ] || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-
-    brew update || exit
+#    #echo "verify Xcode and git are installed"
+#    [ "$(xcode-select -p)"  ] || xcode-select --install
+#    [ "$(which brew)" ] || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+#
+#    brew update || exit
     brew doctor || exit
-    brew upgrade || exit
+#    brew upgrade || exit
     brew install mr vcsh
+    echo ""
+    echo "enter password for manuel:"
+    /usr/local/bin/vcsh clone manuel.local:git/private-vcsh.git private
+
+    # cleanup Git configuration.
+    git config --global --unset user.name
+    git config --global --unset user.email
+    git config --global --unset github.user
+
+    exit
 fi
 
 if [ "$(hostname -s)" = unraid ] ; then
-    cd /usr/bin && ln -sf 'vim' 'vi'
-    mkdir -p ~/src
-    cd ~/src || exit
-    if [ ! -d "vcsh/.git" ] ; then
-        git clone https://github.com/RichiH/vcsh.git
-        cd /usr/local/bin && ln -s ~/src/vcsh/vcsh
+    if [ ! -d "$HOME/.config/vcsh/repo.d/dotfiles.git" ] ; then
+        mv ~/.bash_profile ~.bash_profile.bak
     fi
-    cd ~/src || exit
-    if [ ! -d "myrepos/.git" ] ; then
-        git clone https://github.com/joeyh/myrepos.git
-        cd /usr/local/bin && ln -s ~/src/myrepos/mr
-    fi
-    cd ~/src || exit
-    if [ ! -d "colordiff/.git" ] ; then
-        git clone https://github.com/daveewart/colordiff.git
-        cd /usr/local/bin && ln -s ~/src/colordiff/colordiff.pl colordiff
+    if [ "$(whoami)" = root ] ; then
+        cd /usr/bin && ln -sf 'vim' 'vi'
+        mkdir -p /usr/local/src
+        cd /usr/local/src || exit
+        if [ ! -d "vcsh/.git" ] ; then
+            git clone https://github.com/RichiH/vcsh.git
+            cd /usr/local/bin && ln -sf /usr/local/src/vcsh/vcsh
+        fi
+        cd /usr/local/src || exit
+        if [ ! -d "myrepos/.git" ] ; then
+            git clone https://github.com/joeyh/myrepos.git
+            cd /usr/local/bin && ln -sf /usr/local/src/myrepos/mr
+        fi
+        cd /usr/local/src || exit
+        if [ ! -d "colordiff/.git" ] ; then
+            git clone https://github.com/daveewart/colordiff.git
+            cd /usr/local/bin && ln -sf /usr/local/src/colordiff/colordiff.pl colordiff
+        fi
     fi
 elif [ "$(uname)" = Linux ] ; then
     sudo apt-get update && sudo apt-get install git mr vcsh
+fi
+
+REPOS="git
+mr"
+while read -r REPO; do
+    if [ ! -d "$HOME/.config/vcsh/repo.d/$REPO.git" ] ; then
+        /usr/local/bin/vcsh clone "https://github.com/tomhoover/$REPO-vcsh.git" "$REPO"
+    fi
+done <<EOF
+$REPOS
+EOF
+
+if [ ! "$(hostname -s)" = unraid ] && [ "$(uname)" = Linux ] ; then
+    sudo aptitude install "$(cat ~/.config/apt/installed)"
+    # sudo apt-mark manual $(cat ~/.config/apt/installed) 	# this line is probably not needed, but added for good measure
 fi
 
 if [ ! -d "$HOME/.spf13-vim-3" ] ; then
@@ -42,32 +72,9 @@ else
     vim +BundleInstall! +BundleClean +q
 fi
 
-#if [ ! -r ~/.mrconfig ] ; then
-    #cd $HOME && mr -t -i bootstrap https://raw.githubusercontent.com/tomhoover/mr-castle/master/home/.mrconfig
-#fi
-
-/usr/local/bin/vcsh clone git@github.com:tomhoover/mr-vcsh.git mr
-/usr/local/bin/mr up
-
-#add the following to crontab:
-# @weekly brew list > ~/.config/homebrew/brew.installed
-# @weekly brew cask list > ~/.config/homebrew/cask.installed
-
-if [ "$(uname)" = Darwin ] ; then
-    # shellcheck disable=SC2046
-    brew cask install $(cat ~/.config/homebrew/cask.installed)
-    # shellcheck disable=SC2046
-    brew install $(cat ~/.config/homebrew/brew.installed)
-fi
-
-#add the following to crontab:
-# @weekly comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u) | grep -v ^linux-headers- > ~/.config/apt/installed
-
-if [ ! "$(hostname -s)" = unraid ] && [ "$(uname)" = Linux ] ; then
-    sudo aptitude install "$(cat ~/.config/apt/installed)"
-    # sudo apt-mark manual $(cat ~/.config/apt/installed) 	# this line is probably not needed, but added for good measure
-fi
-
+echo ""
+cd && /usr/local/bin/mr up
 echo ""
 echo "chsh -s $(which zsh)"
+echo ""
 echo "logout and login to re-read configuration"
